# header for coaches
header_coaches = [
    "year",
    "coach_id",
    "coach_name",
    "birthday",
    "birth_location",
    "team_id",
    "games",
    "wins",
    "losses",
    "ties",
    "games_with_team",
    "wins_with_team",
    "losses_with_team",
    "ties_with_team",
    "games_career",
    "wins_career",
    "losses_career",
    "ties_career",
    "playoff_games",
    "playoff_wins",
    "playoff_losses",
    "playoff_games_team",
    "playoff_wins_team",
    "playoff_losses_team",
    "playoff_games_career",
    "playoff_wins_career",
    "playoff_losses_career",
    "remark",
]

# header for stadiums
header_stadiums = [
    "stadium_id",
    "stadium_name",
    "from",
    "to",
    "games",
    "city",
    "state",
    "primary_team",
    "street",
    "surface",
    "super_bowls",
]

# header team standings
header_standings = [
    "year",
    "team_id",
    "team_name",
    "division_id",
    "division",
    "odds_super_bowl",
    "odds_wins",
    "expected_wins",
    "expected_losses",
    "wins",
    "losses",
    "ties",
    "win_pct",
    "points_for",
    "points_against",
    "points_diffential",
    "margin_of_victory",
    "strength_of_schedule",
    "simple_rating_system",
    "offensive_SRS",
    "defensive_SRS",
]
